crashmap.sources = source1
crashmap.channels = channel1
crashmap.sinks = sink1

# Source
crashmap.sources.source1.type = exec
crashmap.sources.source1.command = tail -F /home/anushree/CrashMap/data/stream/accident_stream.csv
crashmap.sources.source1.channels = channel1

# Channel
crashmap.channels.channel1.type = memory
crashmap.channels.channel1.capacity = 10000
crashmap.channels.channel1.transactionCapacity = 1000

# HDFS Sink
crashmap.sinks.sink1.type = hdfs
crashmap.sinks.sink1.hdfs.path = hdfs://localhost:9000/crashmap/flume
crashmap.sinks.sink1.hdfs.filePrefix = accidents
crashmap.sinks.sink1.hdfs.fileSuffix = .csv
crashmap.sinks.sink1.hdfs.fileType = DataStream
crashmap.sinks.sink1.hdfs.writeFormat = Text
crashmap.sinks.sink1.hdfs.rollInterval = 30
crashmap.sinks.sink1.hdfs.rollSize = 0
crashmap.sinks.sink1.hdfs.rollCount = 0
crashmap.sinks.sink1.hdfs.useLocalTimeStamp = true

crashmap.sinks.sink1.channel = channel1
